INFO 2025-09-16 18:27:58,225 autoreload Watching for file changes with StatReloader
INFO 2025-09-16 18:34:30,890 autoreload Watching for file changes with StatReloader
WARNING 2025-09-16 18:34:45,922 exceptions [AdminOrderListView] NotAuthenticated: {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}
Traceback (most recent call last):
  File "C:\Users\sadikturan-PC\Desktop\django-api\.venv\Lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sadikturan-PC\Desktop\django-api\.venv\Lib\site-packages\rest_framework\views.py", line 421, in initial
    self.check_permissions(request)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\sadikturan-PC\Desktop\django-api\.venv\Lib\site-packages\rest_framework\views.py", line 339, in check_permissions
    self.permission_denied(
    ~~~~~~~~~~~~~~~~~~~~~~^
        request,
        ^^^^^^^^
        message=getattr(permission, 'message', None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=getattr(permission, 'code', None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\sadikturan-PC\Desktop\django-api\.venv\Lib\site-packages\rest_framework\views.py", line 180, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
WARNING 2025-09-16 18:34:45,984 log Unauthorized: /api/orders/admin
INFO 2025-09-16 18:36:46,419 autoreload C:\Users\sadikturan-PC\Desktop\django-api\users\views.py changed, reloading.
INFO 2025-09-16 18:36:47,008 autoreload Watching for file changes with StatReloader
INFO 2025-09-16 18:36:49,540 autoreload C:\Users\sadikturan-PC\Desktop\django-api\users\views.py changed, reloading.
INFO 2025-09-16 18:36:50,119 autoreload Watching for file changes with StatReloader
INFO 2025-09-16 18:37:03,024 views User logged in:info (id=1)
